version: '3.8'


services:
  server:
    build: 
      dockerfile: DockerfileServer
    command: /bin/sh -c "while sleep 1000; do :; done"
  client:
    build:
      dockerfile: DockerfileClient
    command: /bin/sh -c "while sleep 1000; do :; done"